#web-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  labels:
    app: web1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web1
  template:
    metadata:
      labels:
        app: web1
    spec:
      containers:
        - name: portal 
          image: garmas2022/garmas-nginx          
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-app1 
spec:
  type: LoadBalancer
  selector:
    app: web1
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
...

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-frontend
spec:
  rules:
    - host: app1.ddns.net 
      http:
        paths:
        - path: /
          backend:
            service:
              name:  svc-app1
              port:
                number: 80
          pathType: Prefix
...  

